branches:
  only:
  - master
sudo: true
dist: xenial
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t alpacked-test-task .
    - docker images
    - docker tag alpacked-test-task $DOCKER_USERNAME/alpacked-test-task
    - docker push $DOCKER_USERNAME/alpacked-test-task
env:
  global:
  - secure: rXxq9t8aeqOFM88/drInK22uJfhfEiIf2z9YUjoAP/VwI8Zx28I2I2JDWG5qGtUfdY7bFUxGkuIeQfDkLS9kTL1ENs1uJ6vGVeTCG3+Jtl7G96+1a4fYQ4nZtbtxu0HaHoJ82LYfbsp+vhJEtLoM5GMQCWyOeWNLZ9EmFKpILNjggNvdPFJODCqOyBIAEVZaXJIqA6q8J6h5fthxfa51zLnQtxshAXkPOJucAAqcaG6XbZADTWeC8s+nED+6wO/jbpTd6YqMXr0R1uSb+8xVCUF/6SjC8A/eByxM73M7HeD/78ESViYmxCVWwuLy8EFjZ15en/RVYaCaZsU8ZxVW+gtihYqhohpbQT+K8e1e++S5Z0VmqW0Fcqg26x1XDJzP9lLBFlZpOV0DRvP0vLcYMUhQ15Wq/TJfWsh8G/ch1JHZvANmd9Sbz+B42cPfOu6qsQIUNntQQtDHECafEAl9FR2C0gYRCLTphaI7UNY1RKW4DYoO2ADtFlq4zuOtDZiVgJzAmgBaVY61rL7CnUXPR5KyA/Xaqlw//og+ED57/3qz22Nu11pFHxzhlg5ISj8/yahYsS0RY+2mRKNNJWLsel3Yu2aeHtCNYGsRytN89D9nmfjnt3HyzhlFcOOyGvjGh4PoAracdGGWe+DJ79+5yCPm7ocNiJ2q9a6ZD30N764=
  - secure: 8XI6OWuQMsqtYir8eYQdZw5jNz7mIiGqge4d1+qsYRGsBCsKVHobXPGxW3pp/VthljiJiAsJ4lZeJtnLn/iNRA5GhkFd4TCtRb5NC9UnMBjOf6pDFI73c3zm84QjjQT6aHRzWHuQOUSD9qYOmHiy3skwKNSHobgUOMwaYbX2/QqxX9LXbXrcpuvQNJ0bWohv1/W5it/5sPrg5R62dKSRpOP2TnCW0TdVLH5GPS3UZ0sGEo1DFTQmOV4TmglXkmSH2tjL7RmO+2hPTL3ikAuFVo9jvVXeaD55KmdVl8SrgI+692Nf09JMVzAjjwxsWgHaNAt3K0J8TIsMjS3+bsLI9RhRrFqIj2/Vj57esLfgnRmWG/CCEBgk9x0A1Y9dsoKt2XcA3vmx2yTYpQLYSgoHE6gyYqtcUWnR2WJD6rprL6Zdq7pUiA/YiLqS981CnxPS9AH89z5MsNQhJ4G05f9kqTF4Up9MYWgd3HrY5S4x4FnPDSAaXQisempQzD6K5bhbCHxeUqnD/Ic8n1+3My3YjP0GC4di81BHKirVdOBZXWwEaK4tGreJ2dApxC4kRNoEAb6eTHvgpZZqbiQC2x/xWEat7tx4Bzz+yGbil0zRT8J31iTreuOeDeDbP1HPnW2SKxmq9y3MtaivQadDRTpqU6g6n63efYSNrhwYobGrB1A=
