branches:
  only:
  - master
sudo: true
dist: xenial
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t alpacked-test-task .
    - docker images
    - docker tag alpacked-test-task $DOCKER_USERNAME/alpacked-test-task
    - docker push $DOCKER_USERNAME/alpacked-test-task
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/alpacked-test-task cat hello.txt
  - script: docker run --rm $DOCKER_USERNAME/alpacked-test-task cat hello.txt
env:
  global:
    secure: rXxq9t8aeqOFM88/drInK22uJfhfEiIf2z9YUjoAP/VwI8Zx28I2I2JDWG5qGtUfdY7bFUxGkuIeQfDkLS9kTL1ENs1uJ6vGVeTCG3+Jtl7G96+1a4fYQ4nZtbtxu0HaHoJ82LYfbsp+vhJEtLoM5GMQCWyOeWNLZ9EmFKpILNjggNvdPFJODCqOyBIAEVZaXJIqA6q8J6h5fthxfa51zLnQtxshAXkPOJucAAqcaG6XbZADTWeC8s+nED+6wO/jbpTd6YqMXr0R1uSb+8xVCUF/6SjC8A/eByxM73M7HeD/78ESViYmxCVWwuLy8EFjZ15en/RVYaCaZsU8ZxVW+gtihYqhohpbQT+K8e1e++S5Z0VmqW0Fcqg26x1XDJzP9lLBFlZpOV0DRvP0vLcYMUhQ15Wq/TJfWsh8G/ch1JHZvANmd9Sbz+B42cPfOu6qsQIUNntQQtDHECafEAl9FR2C0gYRCLTphaI7UNY1RKW4DYoO2ADtFlq4zuOtDZiVgJzAmgBaVY61rL7CnUXPR5KyA/Xaqlw//og+ED57/3qz22Nu11pFHxzhlg5ISj8/yahYsS0RY+2mRKNNJWLsel3Yu2aeHtCNYGsRytN89D9nmfjnt3HyzhlFcOOyGvjGh4PoAracdGGWe+DJ79+5yCPm7ocNiJ2q9a6ZD30N764=
